In [15]:
from categorical_pomap import CategoricalPomap
from pomap.pomap import Pomap

In [16]:
import polars as pl

In [17]:
example_df = pl.from_dict(
    {'cat1': ['a',  'b',],
    'cat2': ['c', 'd', ]}
)

In [18]:
example_df

shape: (2, 2)
┌──────┬──────┐
│ cat1 ┆ cat2 │
│ ---  ┆ ---  │
│ str  ┆ str  │
╞══════╪══════╡
│ a    ┆ c    │
│ b    ┆ d    │
└──────┴──────┘

In [19]:
pmap_cat1 = CategoricalPomap(column='cat1', labels=['a', 'b'])
pmap_cat2 = CategoricalPomap(column='cat2', labels=['c', 'd'])
pmap_cat3 = CategoricalPomap(column='cat2', labels=['e', 'f'])

In [20]:
pmap_prod_12 = pmap_cat1.product(pmap_cat2)

In [21]:
pmap_sum = pmap_cat3.sum(pmap_prod_12)

In [22]:
pmap_prod_12.labels

shape: (4, 2)
┌─────┬────────┐
│     ┆ _right │
│ --- ┆ ---    │
│ str ┆ str    │
╞═════╪════════╡
│ a   ┆ c      │
│ a   ┆ d      │
│ b   ┆ c      │
│ b   ┆ d      │
└─────┴────────┘

In [23]:
pmap_sum.labels

shape: (6, 1)
┌─────┐
│     │
│ --- │
│ str │
╞═════╡
│ e   │
│ f   │
│ a   │
│ b   │
│ c   │
│ d   │
└─────┘