In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from categorical_pomap import CategoricalPomap
from pomap.pomap import Pomap

In [3]:
import polars as pl

In [4]:
example_df = pl.from_dict(
    {'cat1': ['a',  'b',],
    'cat2': ['c', 'd', ]}
)

In [5]:
example_df

shape: (2, 2)
┌──────┬──────┐
│ cat1 ┆ cat2 │
│ ---  ┆ ---  │
│ str  ┆ str  │
╞══════╪══════╡
│ a    ┆ c    │
│ b    ┆ d    │
└──────┴──────┘

In [6]:
pmap_cat1 = CategoricalPomap(column='cat1', labels=['a', 'b'])
pmap_cat2 = CategoricalPomap(column='cat2', labels=['c', 'd'])
pmap_cat3 = CategoricalPomap(column='cat2', labels=['e', 'f'])

In [7]:
pmap_prod_12 = pmap_cat1.product(pmap_cat2)

In [8]:
pmap_sum = pmap_cat3.sum(pmap_prod_12)

In [9]:
pmap_sum.name

"Categorical cat2: ['e', 'f'] + Categorical cat1: ['a', 'b'] x Categorical cat2: ['c', 'd']"

In [10]:
pmap_sum.labels

shape: (6, 2)
┌──────┬──────┐
│ cat2 ┆ cat1 │
│ ---  ┆ ---  │
│ str  ┆ str  │
╞══════╪══════╡
│ e    ┆ null │
│ f    ┆ null │
│ c    ┆ a    │
│ d    ┆ a    │
│ c    ┆ b    │
│ d    ┆ b    │
└──────┴──────┘